apiVersion: v1
kind: Service
metadata:
  name: web1-stateful-service 
  labels:
    app: nginx
spec:
  selector:
    name: {{ .Values.statefulsetservice.name }} 
  ports:
    - port: {{ .Values.statefulsetservice.port }} 
      targetPort: {{ .Values.statefulsetservice.targetPort }} 
      protocol: {{ .Values.statefulsetservice.protocol }} 
  type: {{ .Values.statefulsetservice.type }} 
